name: abap2xlsx-rename

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  rename-abap2xlsx:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Mirror and rename abap2xlsx
        uses: abap2xlsx/abap2xlsx-rename-action@main
        with:
          folder: src/abap2xlsx
          patterns: >
            [
                {
                  "type": "CLAS",
                  "oldName": "zcl_excel_worksheet_pagebreaks",
                  "newName": "zcl_yy_xls_wsheet_pagebreaks"
                },
                {
                  "type": "CLAS",
                  "oldName": "zcl_excel_converter_salv_model",
                  "newName": "zcl_yy_xls_conv_salv_model"
                },
                {
                  "type": "CLAS",
                  "oldName": "zcl_excel_converter_salv_table",
                  "newName": "zcl_yy_xls_conv_salv_table"
                },
                {
                  "type": "CLAS",
                  "oldName": "^zcl_excel$",
                  "newName": "zcl_yy_xls"
                },
                {
                  "type": "CLAS",
                  "oldName": "zcl_excel_(?!(worksheet_pagebreaks|converter_salv_model|converter_salv_table))",
                  "newName": "zcl_yy_xls_"
                },
                {
                  "type": "INTF",
                  "oldName": "zif_excel",
                  "newName": "zif_yy_xls"
                },
                {
                  "type": "CLAS",
                  "oldName": "zcx_excel",
                  "newName": "zcx_yy_xls"
                },
                {
                  "type": "TTYP",
                  "oldName": "zexcel_t",
                  "newName": "zyyy_xls"
                },
                {
                  "type": "TABL",
                  "oldName": "zexcel_s",
                  "newName": "zyys_xls"
                },
                {
                  "type": "DTEL",
                  "oldName": "zexcel_converter_option_subtot",
                  "newName": "zyye_xls_convert_option_subtot"
                },
                {
                  "type": "DTEL",
                  "oldName": "zexcel_converter_option_hidenc",
                  "newName": "zyye_xls_convert_option_hidenc"
                },
                {
                  "type": "DTEL",
                  "oldName": "zexcel_converter_option_hidehd",
                  "newName": "zyye_xls_convert_option_hidehd"
                },
                {
                  "type": "DTEL",
                  "oldName": "zexcel_(?!(converter_option_subtot|converter_option_hidenc|converter_option_hidehd))",
                  "newName": "zyye_xls_"
                },
                {
                  "type": "DOMA",
                  "oldName": "zexcel",
                  "newName": "zyyd_xls"
                },
                {
                  "type": "MSAG",
                  "oldName": "zabap2xlsx",
                  "newName": "zyyxlsmsg"
                }
            ]

      - name: Show changed files
        run: git status

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "ABAP: renamed abap2xlsx"
          branch: automatic/abap2xlsx-rename
          body: |
            Automatic rename of abap2xlsx objects.
